# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_auto_20160124_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('INPUT', 'Entrada'), ('OUTPUT', 'Salida'), ('TRANSFER', 'Transferencia')], max_length=20)),
                ('transaction_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='InventoryMoveDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('inventory_move', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='inventory.InventoryMove')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_move_details', to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='inventorymove',
            name='warehouse',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_moves', to='inventory.Warehouse'),
        ),
    ]
