# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymove',
            name='note',
            field=models.CharField(max_length=320, null=True),
        ),
    ]
