# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-28 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactiondetail',
            old_name='inventory_move',
            new_name='transaction',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('INPUT', 'Entrada'), ('OUTPUT', 'Salida'), (('TRANSFER',), 'Transferencia'), ('SALES_OUTPUT', 'Venta')], max_length=20),
        ),
    ]
