# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-24 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_transaction_transfer_to_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('INPUT', 'Entrada'), ('OUTPUT', 'Salida'), ('TRANSFER', 'Transferencia'), ('SALES_OUTPUT', 'Venta')], max_length=20),
        ),
    ]
