# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorymove_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymove',
            name='note',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
    ]
