# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20160125_1238'),
        ('inventory', '0002_inventorymovedetail_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('last_cost', models.FloatField()),
                ('average_cost', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stock', to='products.Product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stock', to='inventory.Warehouse')),
            ],
        ),
        migrations.AlterField(
            model_name='inventorymove',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_moves', to='inventory.Warehouse'),
        ),
        migrations.AlterField(
            model_name='inventorymovedetail',
            name='inventory_move',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='inventory.InventoryMove'),
        ),
        migrations.AlterField(
            model_name='inventorymovedetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_move_details', to='products.Product'),
        ),
    ]
