# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-27 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20160424_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='is_finish_product',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_quantity',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_of_measure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_units', to='inventory.UnitOfMeasure'),
        ),
    ]
