# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20160125_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='average_cost',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='last_cost',
        ),
    ]
