# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-27 21:40
from __future__ import unicode_literals

from django.db import models, migrations

def default_values(apps,schema_editor):
    UnitOfMeasure = apps.get_model("inventory", "UnitOfMeasure")
    Product = apps.get_model("inventory", "Product")
    unit_of_measure = UnitOfMeasure.objects.create(description='Unidad', abbreviation='Und')
    unit_of_measure.save()

    for product in Product.objects.all():
        product.unit_of_measure =unit_of_measure
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20160527_2122'),
    ]

    operations = [
        migrations.RunPython(default_values)
    ]
