# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20160116_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymove',
            name='Warehouse',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_inventory_move_warehouse', to='inventory.Warehouse'),
        ),
    ]
