# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20160114_2037'),
        ('inventory', '0005_auto_20160116_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMoveDetail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('cost', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='inventorymove',
            name='price',
        ),
        migrations.RemoveField(
            model_name='inventorymove',
            name='quantity_type',
        ),
        migrations.AlterField(
            model_name='inventorymove',
            name='Warehouse',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fk_inventory_move_warehouse', to='inventory.Warehouse'),
        ),
        migrations.AlterField(
            model_name='inventorymove',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='inventorymovedetail',
            name='InventoryMove',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fk_inventory_move_detail_inventory_move', to='inventory.InventoryMove'),
        ),
        migrations.AddField(
            model_name='inventorymovedetail',
            name='Product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fk_inventory_move_detail_product', to='products.Product'),
        ),
    ]
