# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-05 15:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0005_auto_20160527_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('FINISHED', 'Terminado'), ('VOID', 'Nulo')], max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_product_usages', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_product_usages', to='inventory.Warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='ProductUsageDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('included_in_output', models.BooleanField()),
                ('unit_quantity', models.FloatField(default=1)),
                ('old_stock', models.FloatField()),
                ('new_stock', models.FloatField()),
                ('stock_usage', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_usages', to='inventory.Product')),
                ('product_usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='inventory.ProductUsage')),
                ('unit_of_measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_usage_units', to='inventory.UnitOfMeasure')),
            ],
        ),
    ]
