# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 11:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20160116_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymove',
            name='transaction_date',
            field=models.DateField(default=datetime.datetime(2016, 1, 17, 11, 15, 15, 81046, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
