# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventorymove_transaction_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorymove',
            old_name='Warehouse',
            new_name='warehouse',
        ),
    ]
