# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20160114_2037'),
        ('inventory', '0008_auto_20160117_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorymovedetail',
            name='InventoryMove',
        ),
        migrations.RemoveField(
            model_name='inventorymovedetail',
            name='Product',
        ),
        migrations.AddField(
            model_name='inventorymovedetail',
            name='inventory_move',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='inventory.InventoryMove'),
        ),
        migrations.AddField(
            model_name='inventorymovedetail',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_move_details', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='inventorymove',
            name='transaction_type',
            field=models.CharField(choices=[('INPUT', 'Entrada'), ('OUTPUT', 'Salida'), ('TRANSFER', 'Transferencia')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inventorymove',
            name='warehouse',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_moves', to='inventory.Warehouse'),
        ),
    ]
