# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-02 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20160702_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='productusagedetail',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
