# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-09 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_print_on_cashier_shift'),
        ('inventory', '0009_productusagedetail_cost'),
    ]

    operations = [
    ]
