# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-24 23:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashierShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(default=None, null=True)),
                ('close_balance', models.FloatField(null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('CLOSE', 'Cerrado')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_registers', to='inventory.Warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('address', models.CharField(blank=True, max_length=180)),
                ('reference', models.CharField(blank=True, max_length=180)),
                ('phone', models.CharField(db_index=True, max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('number', models.IntegerField()),
                ('clear', models.BooleanField(default=False)),
                ('to_go', models.BooleanField(default=False)),
                ('to_pickup', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('FINISHED', 'Terminado'), ('VOID', 'Nulo')], max_length=15)),
                ('customer_name', models.CharField(blank=True, max_length=70)),
                ('customer_address', models.CharField(blank=True, max_length=180)),
                ('customer_reference', models.CharField(blank=True, max_length=180)),
                ('customer_phone', models.CharField(blank=True, max_length=15)),
                ('update_customer_entry', models.BooleanField(default=False)),
                ('total', models.FloatField()),
                ('cash', models.FloatField()),
                ('customer_change', models.FloatField()),
                ('cashier_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='sales.CashierShift')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('total', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='sales.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_order_details', to='inventory.Product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('cashier_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='sales.CashierShift')),
            ],
        ),
        migrations.CreateModel(
            name='SalesArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='sales_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='sales.SalesArea'),
        ),
        migrations.AddField(
            model_name='cashiershift',
            name='cash_register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashier_shifts', to='sales.CashRegister'),
        ),
        migrations.AddField(
            model_name='cashiershift',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashier_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
