# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-24 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='printed',
            field=models.FloatField(default=False),
        ),
    ]
