# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-27 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashiershift',
            name='start_balance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
