# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20160128_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashiershift',
            name='close_balance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cashiershift',
            name='end_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cashiershift',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
