# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20160129_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashregister',
            name='status',
        ),
        migrations.AddField(
            model_name='cashiershift',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('CLOSE', 'Cerrado')], default='CLOSE', max_length=15),
            preserve_default=False,
        ),
    ]
