# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20160130_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_number',
            new_name='number',
        ),
        migrations.AddField(
            model_name='order',
            name='clear',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='update_customer_entry',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('FINISHED', 'Terminada'), ('VOID', 'Nulo')], max_length=15),
        ),
    ]
