# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_ordernumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernumber',
            name='cashier_shift',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='sales.CashierShift'),
            preserve_default=False,
        ),
    ]
