# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 23:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_ordernumber_cashier_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordernumber',
            name='date',
        ),
    ]
