# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_remove_ordernumber_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='order',
            name='cancel_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='finished_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
