# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_auto_20160204_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='sales_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='sales.SalesArea'),
        ),
    ]
