# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 02:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_auto_20160204_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cancel_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='finished_date',
        ),
    ]
