# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('cost', models.FloatField()),
                ('average_cost', models.FloatField()),
                ('sell_price', models.FloatField()),
                ('show_in_menu', models.BooleanField()),
                ('is_raw_material', models.BooleanField()),
            ],
        ),
    ]
