# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20160124_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='average_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
